from typing import Protocol
from researchd.collaboration.contracts import AgentHealth, AgentInvocationRequest, AgentInvocationResult, AgentRuntime


class AgentAdapter(Protocol):
    async def health(self, runtime: AgentRuntime) -> AgentHealth: ...
    async def invoke(self, request: AgentInvocationRequest) -> AgentInvocationResult: ...
    async def cancel(self, invocation_id: str) -> None: ...
